servicecomb-config-order: 2
APPLICATION_ID: openMec  #应用名
service_description:
  name: toolchain-test  #微服务名
  version: 1.0.0   #微服务版本
  environment: development
servicecomb:
  service:
    registry:
      address: http://service-center:30100  #连接SC(Service Center,注册中心)的地址
  rest:
    address: 0.0.0.0:8058  #Rest通信地址
  cors:
    enabled: true
    origin: "*"
    allowCredentials: false
    allowedMethod: GET,POST,HEAD,OPTIONS,PUT,DELETE
    allowedHeader: x-rest-version,Content-Type,X-Requested-With,accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers,Authorization
    exposedHeader: Location
  uploads:
    directory: /toolchain
    maxSize: -1
