tosca_definitions_version: tosca_simple_profile_for_nfv_1_0_0

description: VmDeployment

topology_template:
  inputs:
    APP1_vcpu:
      default: 1
      description: Number of CPUs for the server.
      type: integer
    APP1_vmemory:
      default: 1024 MB
      description: Number of memory for the server.
      type: scalar-unit.size
    APP1_vstorage:
      default: 1 GB
      description: Size of the storage to be created.
      type: scalar-unit.size
  node_templates:
    # APP IaaS Resources
    APP1:
      type: tosca.nodes.mec.APP
      capabilities:
        nfv_compute:
          properties:
            disk_size: {get_input: APP1_vstorage}
            mem_size: {get_input: APP1_vmemory}
            num_cpus: {get_input: APP1_vcpu}
      properties:
        name: {vm_name}
        block_device_mapping_v2:
          - volume_size: {get_input: APP1_vstorage}
            image: {image_name}
            delete_on_termination: true
        config_drive: true
        user_data_format: RAW

    CP1:
      type: tosca.nodes.mec.CP
      properties:
        management: true
        order: 0
        name: eth0
      requirements:
        - virtualLink:
            node: VL1
        - virtualBinding:
            node: APP1

    VL1:
      type: tosca.nodes.mec.VL
      properties:
        network_name: net1
        vendor: Unicom

  policies:
    - SP1:
        type: tosca.policies.mec.Scaling
        targets: [APP1]
        properties:
          increment: 1
          cooldown: 10
          min_instances: 1
          max_instances: 3
          default_instances: 1
