tosca_definitions_version: tosca_simple_profile_for_nfv_1_0_0
description: MepConfig
topology_template:
  node_templates: 
      # APP Rules
    # DNSRule1:
    #   type: tosca.nodes.mec.DNSRule
    #   properties:
    #     domain_name: app2.edge
    #     plugin_driver:
    #       - etsi2
    #     answers:
    #       - ip: CP1
    #         type: A
    #         ttl: 3600

    # TrafficRule0:
    #   type: tosca.nodes.mec.TrafficRule
    #   properties:
    #     destination_port_high: 255
    #     source_netmask: 32
    #     plugin_driver: etsi2
    #     protocol: 1
    #     destination_port_low: 0
    #     source_port_low: 0
    #     source_port_high: 255
    #     source_ip_address: 10.0.0.1
    #     destination_ip_address: CP1
    #     destination_netmask: 23
    APIAccess1:
      type: tosca.nodes.mec.APIAccess
      properties:
        ip: CP1
        scheme: http
        port: 80
        name: API1
        path: /api

    APIGateway1:
      type: tosca.nodes.mec.APIGateway
      properties:
        group_host: host1.com
        swagger: openapi.yaml
        protocol: http
        plugin_driver: etsi2
        targets:
          - ip: CP1
            port: 80
        group_path: /path1

    ServiceProduced1:
      type: tosca.nodes.mec.ServiceProduced
      properties:
        app_ser_type: IT
        endpoint: APIGateway1
        app_ser_name: sr1
        version: 1.0.0
        type: gw

    HealthCheck1:
      type: tosca.nodes.mec.HealthCheck
      properties:
        module: icmp
        target: CP1
        interval: 30
